{{- $username := .Values.postgresql.postgresqlUsername -}}
{{- $password := .Values.postgresql.postgresqlPassword -}}
{{- $host := .Values.postgresql.postgresqlHost -}}
{{- $port := .Values.postgresql.service.port -}}
{{- $database := .Values.postgresql.postgresqlDatabase -}}
{{- $chartName := .Chart.Name }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $chartName }}-config"
data:
  TEST_ENV: testEnv
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $chartName }}-secret"
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" $username $password $host $port $database  | b64enc | quote }}
  DB_NAME: {{ $database | b64enc | trimAll "\n" | quote }}
  DB_USERNAME: {{ $username | b64enc | trimAll "\n" | quote }}
  DB_PASSWORD: {{ $password | b64enc | trimAll "\n" | quote }}
  DB_PSQL_URL: {{ printf "postgresql://%s:%s@%s/%s" $username $password $host $database | b64enc | trimAll "\n" | quote }}

