{{- $chartName := .Chart.Name }}
{{- $releaseName := .Release.Name }}
{{- $service := .Release.Service }}
{{- $chartVersion := .Chart.Version }}
{{- $appVersion := .Chart.AppVersion }}
{{- $postgresHost := .Values.postgresql.postgresqlHost }}
{{- $postgresPort := .Values.postgresql.postgresqlPort }}


apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $chartName }}-job"
  labels:
    app.kubernetes.io/managed-by: "{{ $service }}"
    app.kubernetes.io/instance: "{{ $chartName }}-job"
    app.kubernetes.io/version: {{ $appVersion }}
    helm.sh/chart: "{{ $chartName }}-{{ $chartVersion }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ $releaseName }}"
      labels:
        app.kubernetes.io/managed-by: "{{ $service }}"
        app.kubernetes.io/instance: "{{ $releaseName }}"
        helm.sh/chart: "{{ $chartName }}-{{ $chartVersion }}"
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: "{{ $postgresHost }}"
            - name: POSTGRES_PORT
              value: "{{ $postgresPort }}"
          command:
            - sh
            - "-c"
            - |
              sleep 15
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: "{{ $postgresHost }}"
            - name: POSTGRES_PORT
              value: "{{ $postgresPort }}"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ $chartName }}-secret"
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ $chartName }}-secret"
                  key: DB_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ $chartName }}-secret"
                  key: DB_NAME
          command:
            - sh
            - "-c"
            - |
              psql postgres://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DATABASE <<'EOF'
                create table client (id bigint primary key, name varchar);
              EOF
  backoffLimit: 0

